name: "Build OCI Container Image For GHCR"

on:
  push:
    branches:
      - main
  # Uncomment to run every Monday at midnight
  # schedule:
  #   - cron: "0 0 * * MON"

jobs:
  build-image:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v5

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: niklasmtj/deno-image
          tags: oci-image
          containerfiles: |
            ./Dockerfile

      - name: Push To Github Container Registry
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io
          username: niklasmtj
          password: ${{ github.token }}
